[package]
name = "nova"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.16"
log = "0.4.17"
multi_log = "0.1.2"
simplelog = "0.12.0"
syslog = "6.0.1"

